name: Welcome to FAB
markdown: kramdown
defaults:
  - scope:
      path: "assets/"
    values:
      headshot: true
collections:
  cans:
    output: true
    navbar: true
  blog_posts:
    output: true
    navbar: true
