name: Welcome to FAB
markdown: kramdown
google_maps_javascript_api_key: "AIzaSyCCK99lIGLXj04Bts-C3nZlcc3HWKvLH6U"
defaults:
  - scope:
      path: "assets/"
    values:
      headshot: true
  -
    scope:
      type: redirects
    values:
      layout: redirect
collections:
  cans:
    output: true
  blog_posts:
    output: true
  redirects:
    output: true
    permalink: /:path/
